// Code generated by go-swagger; DO NOT EDIT.

package runs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	lhttp "github.infra.cloudera.com/CAI/AmpRagMonitoring/pkg/http"
)

// DeleteRunsOKCode is the HTTP code returned for type DeleteRunsOK
const DeleteRunsOKCode int = 200

/*
DeleteRunsOK success

swagger:response deleteRunsOK
*/
type DeleteRunsOK struct {
}

// NewDeleteRunsOK creates DeleteRunsOK with default headers values

func NewDeleteRunsOK() *DeleteRunsOK {

	return &DeleteRunsOK{}
}

// WriteResponse to the client
func (o *DeleteRunsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteRunsBadRequestCode is the HTTP code returned for type DeleteRunsBadRequest
const DeleteRunsBadRequestCode int = 400

/*
DeleteRunsBadRequest bad request

swagger:response deleteRunsBadRequest
*/
type DeleteRunsBadRequest struct {
}

// NewDeleteRunsBadRequest creates DeleteRunsBadRequest with default headers values

func NewDeleteRunsBadRequest() *lhttp.HttpError {
	return &lhttp.HttpError{
		Code: 400,
	}
}

// WriteResponse to the client
func (o *DeleteRunsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// DeleteRunsInternalServerErrorCode is the HTTP code returned for type DeleteRunsInternalServerError
const DeleteRunsInternalServerErrorCode int = 500

/*
DeleteRunsInternalServerError internal service error

swagger:response deleteRunsInternalServerError
*/
type DeleteRunsInternalServerError struct {
}

// NewDeleteRunsInternalServerError creates DeleteRunsInternalServerError with default headers values

func NewDeleteRunsInternalServerError() *lhttp.HttpError {
	return &lhttp.HttpError{
		Code: 500,
	}
}

// WriteResponse to the client
func (o *DeleteRunsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
