// Code generated by go-swagger; DO NOT EDIT.

package runs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteRunsHandlerFunc turns a function with the right signature into a delete runs handler
type DeleteRunsHandlerFunc func(DeleteRunsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteRunsHandlerFunc) Handle(params DeleteRunsParams) middleware.Responder {
	return fn(params)
}

// DeleteRunsHandler interface for that can handle valid delete runs params
type DeleteRunsHandler interface {
	Handle(DeleteRunsParams) middleware.Responder
}

// NewDeleteRuns creates a new http.Handler for the delete runs operation
func NewDeleteRuns(ctx *middleware.Context, handler DeleteRunsHandler) *DeleteRuns {
	return &DeleteRuns{Context: ctx, Handler: handler}
}

/*
	DeleteRuns swagger:route DELETE /runs runs deleteRuns

Delete an experiment run from monitoring.

Delete an experiment run from monitoring.
*/
type DeleteRuns struct {
	Context *middleware.Context
	Handler DeleteRunsHandler
}

func (o *DeleteRuns) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteRunsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
