// Code generated by go-swagger; DO NOT EDIT.

package runs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetRunsParametersHandlerFunc turns a function with the right signature into a get runs parameters handler
type GetRunsParametersHandlerFunc func(GetRunsParametersParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetRunsParametersHandlerFunc) Handle(params GetRunsParametersParams) middleware.Responder {
	return fn(params)
}

// GetRunsParametersHandler interface for that can handle valid get runs parameters params
type GetRunsParametersHandler interface {
	Handle(GetRunsParametersParams) middleware.Responder
}

// NewGetRunsParameters creates a new http.Handler for the get runs parameters operation
func NewGetRunsParameters(ctx *middleware.Context, handler GetRunsParametersHandler) *GetRunsParameters {
	return &GetRunsParameters{Context: ctx, Handler: handler}
}

/*
	GetRunsParameters swagger:route GET /runs/parameters runs getRunsParameters

Get a list of monitored experiment run parameters.

Get a list of monitored experiment run parameters.
*/
type GetRunsParameters struct {
	Context *middleware.Context
	Handler GetRunsParametersHandler
}

func (o *GetRunsParameters) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetRunsParametersParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
