// Code generated by go-swagger; DO NOT EDIT.

package runs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	lhttp "github.infra.cloudera.com/CAI/AmpRagMonitoring/pkg/http"

	"github.infra.cloudera.com/CAI/AmpRagMonitoring/models"
)

// GetRunsParametersOKCode is the HTTP code returned for type GetRunsParametersOK
const GetRunsParametersOKCode int = 200

/*
GetRunsParametersOK success

swagger:response getRunsParametersOK
*/
type GetRunsParametersOK struct {

	/*
	  In: Body
	*/
	Payload []*models.ExperimentRunParameter `json:"body,omitempty"`
}

// NewGetRunsParametersOK creates GetRunsParametersOK with default headers values

func NewGetRunsParametersOK() *GetRunsParametersOK {

	return &GetRunsParametersOK{}
}

// WithPayload adds the payload to the get runs parameters o k response
func (o *GetRunsParametersOK) WithPayload(payload []*models.ExperimentRunParameter) *GetRunsParametersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get runs parameters o k response
func (o *GetRunsParametersOK) SetPayload(payload []*models.ExperimentRunParameter) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRunsParametersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.ExperimentRunParameter, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetRunsParametersBadRequestCode is the HTTP code returned for type GetRunsParametersBadRequest
const GetRunsParametersBadRequestCode int = 400

/*
GetRunsParametersBadRequest bad request

swagger:response getRunsParametersBadRequest
*/
type GetRunsParametersBadRequest struct {
}

// NewGetRunsParametersBadRequest creates GetRunsParametersBadRequest with default headers values

func NewGetRunsParametersBadRequest() *lhttp.HttpError {
	return &lhttp.HttpError{
		Code: 400,
	}
}

// WriteResponse to the client
func (o *GetRunsParametersBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetRunsParametersInternalServerErrorCode is the HTTP code returned for type GetRunsParametersInternalServerError
const GetRunsParametersInternalServerErrorCode int = 500

/*
GetRunsParametersInternalServerError internal service error

swagger:response getRunsParametersInternalServerError
*/
type GetRunsParametersInternalServerError struct {
}

// NewGetRunsParametersInternalServerError creates GetRunsParametersInternalServerError with default headers values

func NewGetRunsParametersInternalServerError() *lhttp.HttpError {
	return &lhttp.HttpError{
		Code: 500,
	}
}

// WriteResponse to the client
func (o *GetRunsParametersInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
