// Code generated by go-swagger; DO NOT EDIT.

package runs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	lhttp "github.infra.cloudera.com/CAI/AmpRagMonitoring/pkg/http"

	"github.infra.cloudera.com/CAI/AmpRagMonitoring/models"
)

// PostRunsOKCode is the HTTP code returned for type PostRunsOK
const PostRunsOKCode int = 200

/*
PostRunsOK success

swagger:response postRunsOK
*/
type PostRunsOK struct {

	/*
	  In: Body
	*/
	Payload *models.ExperimentRun `json:"body,omitempty"`
}

// NewPostRunsOK creates PostRunsOK with default headers values

func NewPostRunsOK() *PostRunsOK {

	return &PostRunsOK{}
}

// WithPayload adds the payload to the post runs o k response
func (o *PostRunsOK) WithPayload(payload *models.ExperimentRun) *PostRunsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post runs o k response
func (o *PostRunsOK) SetPayload(payload *models.ExperimentRun) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostRunsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostRunsBadRequestCode is the HTTP code returned for type PostRunsBadRequest
const PostRunsBadRequestCode int = 400

/*
PostRunsBadRequest bad request

swagger:response postRunsBadRequest
*/
type PostRunsBadRequest struct {
}

// NewPostRunsBadRequest creates PostRunsBadRequest with default headers values

func NewPostRunsBadRequest() *lhttp.HttpError {
	return &lhttp.HttpError{
		Code: 400,
	}
}

// WriteResponse to the client
func (o *PostRunsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PostRunsInternalServerErrorCode is the HTTP code returned for type PostRunsInternalServerError
const PostRunsInternalServerErrorCode int = 500

/*
PostRunsInternalServerError internal service error

swagger:response postRunsInternalServerError
*/
type PostRunsInternalServerError struct {
}

// NewPostRunsInternalServerError creates PostRunsInternalServerError with default headers values

func NewPostRunsInternalServerError() *lhttp.HttpError {
	return &lhttp.HttpError{
		Code: 500,
	}
}

// WriteResponse to the client
func (o *PostRunsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
