CREATE TABLE IF NOT EXISTS metrics (
    id INTEGER PRIMARY KEY,
    experiment_id VARCHAR(100) NOT NULL,
    run_id VARCHAR(100) NOT NULL,
    name VARCHAR(100) NOT NULL,
    value REAL NOT NULL,
    tags TEXT,
    ts TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
