// Code generated by go-swagger; DO NOT EDIT.

package runs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	lswagger "github.infra.cloudera.com/CAI/AmpRagMonitoring/pkg/swagger"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteRunsReader is a Reader for the DeleteRuns structure.
type DeleteRunsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteRunsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteRunsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteRunsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteRunsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteRunsOK creates a DeleteRunsOK with default headers values
func NewDeleteRunsOK() *DeleteRunsOK {
	return &DeleteRunsOK{}
}

/*
DeleteRunsOK handles this case with default header values.

success
*/
type DeleteRunsOK struct {
}

// Code gets the status code for the delete runs o k response
func (o *DeleteRunsOK) Code() int {
	return 200
}

func (o *DeleteRunsOK) Error() string {
	return fmt.Sprintf("[DELETE /runs][%d] deleteRunsOK ", 200)
}

func (o *DeleteRunsOK) GetSerializedPayload() ([]byte, error) {
	return nil, nil
}

var _ lswagger.SwaggerResponse = &DeleteRunsOK{}

func (o *DeleteRunsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteRunsBadRequest creates a DeleteRunsBadRequest with default headers values
func NewDeleteRunsBadRequest() *DeleteRunsBadRequest {
	return &DeleteRunsBadRequest{}
}

/*
DeleteRunsBadRequest handles this case with default header values.

bad request
*/
type DeleteRunsBadRequest struct {
}

// Code gets the status code for the delete runs bad request response
func (o *DeleteRunsBadRequest) Code() int {
	return 400
}

func (o *DeleteRunsBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /runs][%d] deleteRunsBadRequest ", 400)
}

func (o *DeleteRunsBadRequest) GetSerializedPayload() ([]byte, error) {
	return nil, nil
}

var _ lswagger.SwaggerResponse = &DeleteRunsBadRequest{}

func (o *DeleteRunsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteRunsInternalServerError creates a DeleteRunsInternalServerError with default headers values
func NewDeleteRunsInternalServerError() *DeleteRunsInternalServerError {
	return &DeleteRunsInternalServerError{}
}

/*
DeleteRunsInternalServerError handles this case with default header values.

internal service error
*/
type DeleteRunsInternalServerError struct {
}

// Code gets the status code for the delete runs internal server error response
func (o *DeleteRunsInternalServerError) Code() int {
	return 500
}

func (o *DeleteRunsInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /runs][%d] deleteRunsInternalServerError ", 500)
}

func (o *DeleteRunsInternalServerError) GetSerializedPayload() ([]byte, error) {
	return nil, nil
}

var _ lswagger.SwaggerResponse = &DeleteRunsInternalServerError{}

func (o *DeleteRunsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
