// Code generated by go-swagger; DO NOT EDIT.

package runs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	lswagger "github.infra.cloudera.com/CAI/AmpRagMonitoring/pkg/swagger"

	strfmt "github.com/go-openapi/strfmt"

	"github.infra.cloudera.com/CAI/AmpRagMonitoring/models"
)

// GetRunsParametersReader is a Reader for the GetRunsParameters structure.
type GetRunsParametersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRunsParametersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetRunsParametersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetRunsParametersBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetRunsParametersInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetRunsParametersOK creates a GetRunsParametersOK with default headers values
func NewGetRunsParametersOK() *GetRunsParametersOK {
	return &GetRunsParametersOK{}
}

/*
GetRunsParametersOK handles this case with default header values.

success
*/
type GetRunsParametersOK struct {
	Payload []*models.ExperimentRunParameter
}

// Code gets the status code for the get runs parameters o k response
func (o *GetRunsParametersOK) Code() int {
	return 200
}

func (o *GetRunsParametersOK) Error() string {
	return fmt.Sprintf("[GET /runs/parameters][%d] getRunsParametersOK  %+v", 200, o.Payload)
}

func (o *GetRunsParametersOK) GetPayload() []*models.ExperimentRunParameter {
	return o.Payload
}

func (o *GetRunsParametersOK) GetSerializedPayload() ([]byte, error) {
	return json.Marshal(o.Payload)
}

var _ lswagger.SwaggerResponse = &GetRunsParametersOK{}

func (o *GetRunsParametersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRunsParametersBadRequest creates a GetRunsParametersBadRequest with default headers values
func NewGetRunsParametersBadRequest() *GetRunsParametersBadRequest {
	return &GetRunsParametersBadRequest{}
}

/*
GetRunsParametersBadRequest handles this case with default header values.

bad request
*/
type GetRunsParametersBadRequest struct {
}

// Code gets the status code for the get runs parameters bad request response
func (o *GetRunsParametersBadRequest) Code() int {
	return 400
}

func (o *GetRunsParametersBadRequest) Error() string {
	return fmt.Sprintf("[GET /runs/parameters][%d] getRunsParametersBadRequest ", 400)
}

func (o *GetRunsParametersBadRequest) GetSerializedPayload() ([]byte, error) {
	return nil, nil
}

var _ lswagger.SwaggerResponse = &GetRunsParametersBadRequest{}

func (o *GetRunsParametersBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetRunsParametersInternalServerError creates a GetRunsParametersInternalServerError with default headers values
func NewGetRunsParametersInternalServerError() *GetRunsParametersInternalServerError {
	return &GetRunsParametersInternalServerError{}
}

/*
GetRunsParametersInternalServerError handles this case with default header values.

internal service error
*/
type GetRunsParametersInternalServerError struct {
}

// Code gets the status code for the get runs parameters internal server error response
func (o *GetRunsParametersInternalServerError) Code() int {
	return 500
}

func (o *GetRunsParametersInternalServerError) Error() string {
	return fmt.Sprintf("[GET /runs/parameters][%d] getRunsParametersInternalServerError ", 500)
}

func (o *GetRunsParametersInternalServerError) GetSerializedPayload() ([]byte, error) {
	return nil, nil
}

var _ lswagger.SwaggerResponse = &GetRunsParametersInternalServerError{}

func (o *GetRunsParametersInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
