// Code generated by go-swagger; DO NOT EDIT.

package runs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	lswagger "github.infra.cloudera.com/CAI/AmpRagMonitoring/pkg/swagger"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRunsParametersParams creates a new GetRunsParametersParams object
// with the default values initialized.
func NewGetRunsParametersParams() *GetRunsParametersParams {
	var ()
	return &GetRunsParametersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRunsParametersParamsWithTimeout creates a new GetRunsParametersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRunsParametersParamsWithTimeout(timeout time.Duration) *GetRunsParametersParams {
	var ()
	return &GetRunsParametersParams{

		timeout: timeout,
	}
}

// NewGetRunsParametersParamsWithContext creates a new GetRunsParametersParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRunsParametersParamsWithContext(ctx context.Context) *GetRunsParametersParams {
	var ()
	return &GetRunsParametersParams{

		Context: ctx,
	}
}

// NewGetRunsParametersParamsWithHTTPClient creates a new GetRunsParametersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRunsParametersParamsWithHTTPClient(client *http.Client) *GetRunsParametersParams {
	var ()
	return &GetRunsParametersParams{
		HTTPClient: client,
	}
}

/*
GetRunsParametersParams contains all the parameters to send to the API endpoint
for the get runs parameters operation typically these are written to a http.Request
*/
type GetRunsParametersParams struct {

	/*ExperimentID
	  The ID of the experiment

	*/
	ExperimentID *string
	/*RunID
	  The ID of the run

	*/
	RunID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

var _ lswagger.SwaggerParams = &GetRunsParametersParams{}

func (o *GetRunsParametersParams) GetSerializedParams() ([]byte, error) {
	var params = struct {
		ExperimentID *string

		RunID *string
	}{

		ExperimentID: o.ExperimentID,

		RunID: o.RunID,
	}

	return json.Marshal(&params)
}

// WithTimeout adds the timeout to the get runs parameters params
func (o *GetRunsParametersParams) WithTimeout(timeout time.Duration) *GetRunsParametersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get runs parameters params
func (o *GetRunsParametersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get runs parameters params
func (o *GetRunsParametersParams) WithContext(ctx context.Context) *GetRunsParametersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get runs parameters params
func (o *GetRunsParametersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get runs parameters params
func (o *GetRunsParametersParams) WithHTTPClient(client *http.Client) *GetRunsParametersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get runs parameters params
func (o *GetRunsParametersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithExperimentID adds the experimentID to the get runs parameters params
func (o *GetRunsParametersParams) WithExperimentID(experimentID *string) *GetRunsParametersParams {
	o.SetExperimentID(experimentID)
	return o
}

// SetExperimentID adds the experimentId to the get runs parameters params
func (o *GetRunsParametersParams) SetExperimentID(experimentID *string) {
	o.ExperimentID = experimentID
}

// WithRunID adds the runID to the get runs parameters params
func (o *GetRunsParametersParams) WithRunID(runID *string) *GetRunsParametersParams {
	o.SetRunID(runID)
	return o
}

// SetRunID adds the runId to the get runs parameters params
func (o *GetRunsParametersParams) SetRunID(runID *string) {
	o.RunID = runID
}

// WriteToRequest writes these params to a swagger request
func (o *GetRunsParametersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ExperimentID != nil {

		// query param experiment_id
		var qrExperimentID string
		if o.ExperimentID != nil {
			qrExperimentID = *o.ExperimentID
		}
		qExperimentID := qrExperimentID
		if qExperimentID != "" {
			if err := r.SetQueryParam("experiment_id", qExperimentID); err != nil {
				return err
			}
		}

	}

	if o.RunID != nil {

		// query param run_id
		var qrRunID string
		if o.RunID != nil {
			qrRunID = *o.RunID
		}
		qRunID := qrRunID
		if qRunID != "" {
			if err := r.SetQueryParam("run_id", qRunID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
