// Code generated by go-swagger; DO NOT EDIT.

package runs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	lswagger "github.infra.cloudera.com/CAI/AmpRagMonitoring/pkg/swagger"

	strfmt "github.com/go-openapi/strfmt"

	"github.infra.cloudera.com/CAI/AmpRagMonitoring/models"
)

// NewPostRunsParams creates a new PostRunsParams object
// with the default values initialized.
func NewPostRunsParams() *PostRunsParams {
	var ()
	return &PostRunsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostRunsParamsWithTimeout creates a new PostRunsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostRunsParamsWithTimeout(timeout time.Duration) *PostRunsParams {
	var ()
	return &PostRunsParams{

		timeout: timeout,
	}
}

// NewPostRunsParamsWithContext creates a new PostRunsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostRunsParamsWithContext(ctx context.Context) *PostRunsParams {
	var ()
	return &PostRunsParams{

		Context: ctx,
	}
}

// NewPostRunsParamsWithHTTPClient creates a new PostRunsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostRunsParamsWithHTTPClient(client *http.Client) *PostRunsParams {
	var ()
	return &PostRunsParams{
		HTTPClient: client,
	}
}

/*
PostRunsParams contains all the parameters to send to the API endpoint
for the post runs operation typically these are written to a http.Request
*/
type PostRunsParams struct {

	/*Body*/
	Body *models.ExperimentRun

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

var _ lswagger.SwaggerParams = &PostRunsParams{}

func (o *PostRunsParams) GetSerializedParams() ([]byte, error) {
	var params = struct {
		Body *models.ExperimentRun
	}{

		Body: o.Body,
	}

	return json.Marshal(&params)
}

// WithTimeout adds the timeout to the post runs params
func (o *PostRunsParams) WithTimeout(timeout time.Duration) *PostRunsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post runs params
func (o *PostRunsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post runs params
func (o *PostRunsParams) WithContext(ctx context.Context) *PostRunsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post runs params
func (o *PostRunsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post runs params
func (o *PostRunsParams) WithHTTPClient(client *http.Client) *PostRunsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post runs params
func (o *PostRunsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post runs params
func (o *PostRunsParams) WithBody(body *models.ExperimentRun) *PostRunsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post runs params
func (o *PostRunsParams) SetBody(body *models.ExperimentRun) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostRunsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
