// Code generated by go-swagger; DO NOT EDIT.

package runs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	lswagger "github.infra.cloudera.com/CAI/AmpRagMonitoring/pkg/swagger"

	strfmt "github.com/go-openapi/strfmt"

	"github.infra.cloudera.com/CAI/AmpRagMonitoring/models"
)

// NewPostRunsListParams creates a new PostRunsListParams object
// with the default values initialized.
func NewPostRunsListParams() *PostRunsListParams {
	var ()
	return &PostRunsListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostRunsListParamsWithTimeout creates a new PostRunsListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostRunsListParamsWithTimeout(timeout time.Duration) *PostRunsListParams {
	var ()
	return &PostRunsListParams{

		timeout: timeout,
	}
}

// NewPostRunsListParamsWithContext creates a new PostRunsListParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostRunsListParamsWithContext(ctx context.Context) *PostRunsListParams {
	var ()
	return &PostRunsListParams{

		Context: ctx,
	}
}

// NewPostRunsListParamsWithHTTPClient creates a new PostRunsListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostRunsListParamsWithHTTPClient(client *http.Client) *PostRunsListParams {
	var ()
	return &PostRunsListParams{
		HTTPClient: client,
	}
}

/*
PostRunsListParams contains all the parameters to send to the API endpoint
for the post runs list operation typically these are written to a http.Request
*/
type PostRunsListParams struct {

	/*Body*/
	Body *models.ExperimentRunListFilter

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

var _ lswagger.SwaggerParams = &PostRunsListParams{}

func (o *PostRunsListParams) GetSerializedParams() ([]byte, error) {
	var params = struct {
		Body *models.ExperimentRunListFilter
	}{

		Body: o.Body,
	}

	return json.Marshal(&params)
}

// WithTimeout adds the timeout to the post runs list params
func (o *PostRunsListParams) WithTimeout(timeout time.Duration) *PostRunsListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post runs list params
func (o *PostRunsListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post runs list params
func (o *PostRunsListParams) WithContext(ctx context.Context) *PostRunsListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post runs list params
func (o *PostRunsListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post runs list params
func (o *PostRunsListParams) WithHTTPClient(client *http.Client) *PostRunsListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post runs list params
func (o *PostRunsListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post runs list params
func (o *PostRunsListParams) WithBody(body *models.ExperimentRunListFilter) *PostRunsListParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post runs list params
func (o *PostRunsListParams) SetBody(body *models.ExperimentRunListFilter) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostRunsListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
