// Code generated by go-swagger; DO NOT EDIT.

package metrics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	lswagger "github.infra.cloudera.com/CAI/AmpRagMonitoring/pkg/swagger"

	strfmt "github.com/go-openapi/strfmt"
)

// GetMetricsNamesReader is a Reader for the GetMetricsNames structure.
type GetMetricsNamesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMetricsNamesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetMetricsNamesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetMetricsNamesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetMetricsNamesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetMetricsNamesOK creates a GetMetricsNamesOK with default headers values
func NewGetMetricsNamesOK() *GetMetricsNamesOK {
	return &GetMetricsNamesOK{}
}

/*
GetMetricsNamesOK handles this case with default header values.

success
*/
type GetMetricsNamesOK struct {
	Payload []string
}

// Code gets the status code for the get metrics names o k response
func (o *GetMetricsNamesOK) Code() int {
	return 200
}

func (o *GetMetricsNamesOK) Error() string {
	return fmt.Sprintf("[GET /metrics/names][%d] getMetricsNamesOK  %+v", 200, o.Payload)
}

func (o *GetMetricsNamesOK) GetPayload() []string {
	return o.Payload
}

func (o *GetMetricsNamesOK) GetSerializedPayload() ([]byte, error) {
	return json.Marshal(o.Payload)
}

var _ lswagger.SwaggerResponse = &GetMetricsNamesOK{}

func (o *GetMetricsNamesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetMetricsNamesBadRequest creates a GetMetricsNamesBadRequest with default headers values
func NewGetMetricsNamesBadRequest() *GetMetricsNamesBadRequest {
	return &GetMetricsNamesBadRequest{}
}

/*
GetMetricsNamesBadRequest handles this case with default header values.

bad request
*/
type GetMetricsNamesBadRequest struct {
}

// Code gets the status code for the get metrics names bad request response
func (o *GetMetricsNamesBadRequest) Code() int {
	return 400
}

func (o *GetMetricsNamesBadRequest) Error() string {
	return fmt.Sprintf("[GET /metrics/names][%d] getMetricsNamesBadRequest ", 400)
}

func (o *GetMetricsNamesBadRequest) GetSerializedPayload() ([]byte, error) {
	return nil, nil
}

var _ lswagger.SwaggerResponse = &GetMetricsNamesBadRequest{}

func (o *GetMetricsNamesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetMetricsNamesInternalServerError creates a GetMetricsNamesInternalServerError with default headers values
func NewGetMetricsNamesInternalServerError() *GetMetricsNamesInternalServerError {
	return &GetMetricsNamesInternalServerError{}
}

/*
GetMetricsNamesInternalServerError handles this case with default header values.

internal service error
*/
type GetMetricsNamesInternalServerError struct {
}

// Code gets the status code for the get metrics names internal server error response
func (o *GetMetricsNamesInternalServerError) Code() int {
	return 500
}

func (o *GetMetricsNamesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /metrics/names][%d] getMetricsNamesInternalServerError ", 500)
}

func (o *GetMetricsNamesInternalServerError) GetSerializedPayload() ([]byte, error) {
	return nil, nil
}

var _ lswagger.SwaggerResponse = &GetMetricsNamesInternalServerError{}

func (o *GetMetricsNamesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
