// Code generated by go-swagger; DO NOT EDIT.

package metrics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	lswagger "github.infra.cloudera.com/CAI/AmpRagMonitoring/pkg/swagger"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetMetricsNamesParams creates a new GetMetricsNamesParams object
// with the default values initialized.
func NewGetMetricsNamesParams() *GetMetricsNamesParams {
	var ()
	return &GetMetricsNamesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetMetricsNamesParamsWithTimeout creates a new GetMetricsNamesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetMetricsNamesParamsWithTimeout(timeout time.Duration) *GetMetricsNamesParams {
	var ()
	return &GetMetricsNamesParams{

		timeout: timeout,
	}
}

// NewGetMetricsNamesParamsWithContext creates a new GetMetricsNamesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetMetricsNamesParamsWithContext(ctx context.Context) *GetMetricsNamesParams {
	var ()
	return &GetMetricsNamesParams{

		Context: ctx,
	}
}

// NewGetMetricsNamesParamsWithHTTPClient creates a new GetMetricsNamesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetMetricsNamesParamsWithHTTPClient(client *http.Client) *GetMetricsNamesParams {
	var ()
	return &GetMetricsNamesParams{
		HTTPClient: client,
	}
}

/*
GetMetricsNamesParams contains all the parameters to send to the API endpoint
for the get metrics names operation typically these are written to a http.Request
*/
type GetMetricsNamesParams struct {

	/*ExperimentID
	  The ID of the experiment

	*/
	ExperimentID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

var _ lswagger.SwaggerParams = &GetMetricsNamesParams{}

func (o *GetMetricsNamesParams) GetSerializedParams() ([]byte, error) {
	var params = struct {
		ExperimentID *string
	}{

		ExperimentID: o.ExperimentID,
	}

	return json.Marshal(&params)
}

// WithTimeout adds the timeout to the get metrics names params
func (o *GetMetricsNamesParams) WithTimeout(timeout time.Duration) *GetMetricsNamesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get metrics names params
func (o *GetMetricsNamesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get metrics names params
func (o *GetMetricsNamesParams) WithContext(ctx context.Context) *GetMetricsNamesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get metrics names params
func (o *GetMetricsNamesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get metrics names params
func (o *GetMetricsNamesParams) WithHTTPClient(client *http.Client) *GetMetricsNamesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get metrics names params
func (o *GetMetricsNamesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithExperimentID adds the experimentID to the get metrics names params
func (o *GetMetricsNamesParams) WithExperimentID(experimentID *string) *GetMetricsNamesParams {
	o.SetExperimentID(experimentID)
	return o
}

// SetExperimentID adds the experimentId to the get metrics names params
func (o *GetMetricsNamesParams) SetExperimentID(experimentID *string) {
	o.ExperimentID = experimentID
}

// WriteToRequest writes these params to a swagger request
func (o *GetMetricsNamesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ExperimentID != nil {

		// query param experiment_id
		var qrExperimentID string
		if o.ExperimentID != nil {
			qrExperimentID = *o.ExperimentID
		}
		qExperimentID := qrExperimentID
		if qExperimentID != "" {
			if err := r.SetQueryParam("experiment_id", qExperimentID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
