// Code generated by go-swagger; DO NOT EDIT.

package metrics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	lswagger "github.infra.cloudera.com/CAI/AmpRagMonitoring/pkg/swagger"

	strfmt "github.com/go-openapi/strfmt"
)

// PostMetricsReader is a Reader for the PostMetrics structure.
type PostMetricsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostMetricsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostMetricsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostMetricsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostMetricsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostMetricsOK creates a PostMetricsOK with default headers values
func NewPostMetricsOK() *PostMetricsOK {
	return &PostMetricsOK{}
}

/*
PostMetricsOK handles this case with default header values.

success
*/
type PostMetricsOK struct {
}

// Code gets the status code for the post metrics o k response
func (o *PostMetricsOK) Code() int {
	return 200
}

func (o *PostMetricsOK) Error() string {
	return fmt.Sprintf("[POST /metrics][%d] postMetricsOK ", 200)
}

func (o *PostMetricsOK) GetSerializedPayload() ([]byte, error) {
	return nil, nil
}

var _ lswagger.SwaggerResponse = &PostMetricsOK{}

func (o *PostMetricsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostMetricsBadRequest creates a PostMetricsBadRequest with default headers values
func NewPostMetricsBadRequest() *PostMetricsBadRequest {
	return &PostMetricsBadRequest{}
}

/*
PostMetricsBadRequest handles this case with default header values.

bad request
*/
type PostMetricsBadRequest struct {
}

// Code gets the status code for the post metrics bad request response
func (o *PostMetricsBadRequest) Code() int {
	return 400
}

func (o *PostMetricsBadRequest) Error() string {
	return fmt.Sprintf("[POST /metrics][%d] postMetricsBadRequest ", 400)
}

func (o *PostMetricsBadRequest) GetSerializedPayload() ([]byte, error) {
	return nil, nil
}

var _ lswagger.SwaggerResponse = &PostMetricsBadRequest{}

func (o *PostMetricsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostMetricsInternalServerError creates a PostMetricsInternalServerError with default headers values
func NewPostMetricsInternalServerError() *PostMetricsInternalServerError {
	return &PostMetricsInternalServerError{}
}

/*
PostMetricsInternalServerError handles this case with default header values.

internal service error
*/
type PostMetricsInternalServerError struct {
}

// Code gets the status code for the post metrics internal server error response
func (o *PostMetricsInternalServerError) Code() int {
	return 500
}

func (o *PostMetricsInternalServerError) Error() string {
	return fmt.Sprintf("[POST /metrics][%d] postMetricsInternalServerError ", 500)
}

func (o *PostMetricsInternalServerError) GetSerializedPayload() ([]byte, error) {
	return nil, nil
}

var _ lswagger.SwaggerResponse = &PostMetricsInternalServerError{}

func (o *PostMetricsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
