// Code generated by go-swagger; DO NOT EDIT.

package metrics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	lswagger "github.infra.cloudera.com/CAI/AmpRagMonitoring/pkg/swagger"

	strfmt "github.com/go-openapi/strfmt"

	"github.infra.cloudera.com/CAI/AmpRagMonitoring/models"
)

// NewPostMetricsParams creates a new PostMetricsParams object
// with the default values initialized.
func NewPostMetricsParams() *PostMetricsParams {
	var ()
	return &PostMetricsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostMetricsParamsWithTimeout creates a new PostMetricsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostMetricsParamsWithTimeout(timeout time.Duration) *PostMetricsParams {
	var ()
	return &PostMetricsParams{

		timeout: timeout,
	}
}

// NewPostMetricsParamsWithContext creates a new PostMetricsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostMetricsParamsWithContext(ctx context.Context) *PostMetricsParams {
	var ()
	return &PostMetricsParams{

		Context: ctx,
	}
}

// NewPostMetricsParamsWithHTTPClient creates a new PostMetricsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostMetricsParamsWithHTTPClient(client *http.Client) *PostMetricsParams {
	var ()
	return &PostMetricsParams{
		HTTPClient: client,
	}
}

/*
PostMetricsParams contains all the parameters to send to the API endpoint
for the post metrics operation typically these are written to a http.Request
*/
type PostMetricsParams struct {

	/*Body*/
	Body *models.Metrics

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

var _ lswagger.SwaggerParams = &PostMetricsParams{}

func (o *PostMetricsParams) GetSerializedParams() ([]byte, error) {
	var params = struct {
		Body *models.Metrics
	}{

		Body: o.Body,
	}

	return json.Marshal(&params)
}

// WithTimeout adds the timeout to the post metrics params
func (o *PostMetricsParams) WithTimeout(timeout time.Duration) *PostMetricsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post metrics params
func (o *PostMetricsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post metrics params
func (o *PostMetricsParams) WithContext(ctx context.Context) *PostMetricsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post metrics params
func (o *PostMetricsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post metrics params
func (o *PostMetricsParams) WithHTTPClient(client *http.Client) *PostMetricsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post metrics params
func (o *PostMetricsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post metrics params
func (o *PostMetricsParams) WithBody(body *models.Metrics) *PostMetricsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post metrics params
func (o *PostMetricsParams) SetBody(body *models.Metrics) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostMetricsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
