// Code generated by go-swagger; DO NOT EDIT.

package metrics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	lswagger "github.infra.cloudera.com/CAI/AmpRagMonitoring/pkg/swagger"

	strfmt "github.com/go-openapi/strfmt"

	"github.infra.cloudera.com/CAI/AmpRagMonitoring/models"
)

// PostMetricsListReader is a Reader for the PostMetricsList structure.
type PostMetricsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostMetricsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostMetricsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostMetricsListBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostMetricsListInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostMetricsListOK creates a PostMetricsListOK with default headers values
func NewPostMetricsListOK() *PostMetricsListOK {
	return &PostMetricsListOK{}
}

/*
PostMetricsListOK handles this case with default header values.

success
*/
type PostMetricsListOK struct {
	Payload []*models.Metric
}

// Code gets the status code for the post metrics list o k response
func (o *PostMetricsListOK) Code() int {
	return 200
}

func (o *PostMetricsListOK) Error() string {
	return fmt.Sprintf("[POST /metrics/list][%d] postMetricsListOK  %+v", 200, o.Payload)
}

func (o *PostMetricsListOK) GetPayload() []*models.Metric {
	return o.Payload
}

func (o *PostMetricsListOK) GetSerializedPayload() ([]byte, error) {
	return json.Marshal(o.Payload)
}

var _ lswagger.SwaggerResponse = &PostMetricsListOK{}

func (o *PostMetricsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostMetricsListBadRequest creates a PostMetricsListBadRequest with default headers values
func NewPostMetricsListBadRequest() *PostMetricsListBadRequest {
	return &PostMetricsListBadRequest{}
}

/*
PostMetricsListBadRequest handles this case with default header values.

bad request
*/
type PostMetricsListBadRequest struct {
}

// Code gets the status code for the post metrics list bad request response
func (o *PostMetricsListBadRequest) Code() int {
	return 400
}

func (o *PostMetricsListBadRequest) Error() string {
	return fmt.Sprintf("[POST /metrics/list][%d] postMetricsListBadRequest ", 400)
}

func (o *PostMetricsListBadRequest) GetSerializedPayload() ([]byte, error) {
	return nil, nil
}

var _ lswagger.SwaggerResponse = &PostMetricsListBadRequest{}

func (o *PostMetricsListBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostMetricsListInternalServerError creates a PostMetricsListInternalServerError with default headers values
func NewPostMetricsListInternalServerError() *PostMetricsListInternalServerError {
	return &PostMetricsListInternalServerError{}
}

/*
PostMetricsListInternalServerError handles this case with default header values.

internal service error
*/
type PostMetricsListInternalServerError struct {
}

// Code gets the status code for the post metrics list internal server error response
func (o *PostMetricsListInternalServerError) Code() int {
	return 500
}

func (o *PostMetricsListInternalServerError) Error() string {
	return fmt.Sprintf("[POST /metrics/list][%d] postMetricsListInternalServerError ", 500)
}

func (o *PostMetricsListInternalServerError) GetSerializedPayload() ([]byte, error) {
	return nil, nil
}

var _ lswagger.SwaggerResponse = &PostMetricsListInternalServerError{}

func (o *PostMetricsListInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
