// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Metrics
//
//	API for creating and fetching metrics
//	Schemes:
//	  http
//	Host: localhost:3000
//	BasePath: /
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
