// Code generated by go-swagger; DO NOT EDIT.

package metrics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetMetricsNamesParams creates a new GetMetricsNamesParams object
// no default values defined in spec.
func NewGetMetricsNamesParams() GetMetricsNamesParams {

	return GetMetricsNamesParams{}
}

// GetMetricsNamesParams contains all the bound params for the get metrics names operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetMetricsNames
type GetMetricsNamesParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The ID of the experiment
	  In: query
	*/
	ExperimentID *string `json:"experiment_id,omitempty"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetMetricsNamesParams() beforehand.
func (o *GetMetricsNamesParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qExperimentID, qhkExperimentID, _ := qs.GetOK("experiment_id")
	if err := o.bindExperimentID(qExperimentID, qhkExperimentID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindExperimentID binds and validates parameter ExperimentID from query.
func (o *GetMetricsNamesParams) bindExperimentID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.ExperimentID = &raw

	return nil
}
