// Code generated by go-swagger; DO NOT EDIT.

package metrics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	lhttp "github.infra.cloudera.com/CAI/AmpRagMonitoring/pkg/http"
)

// GetMetricsNamesOKCode is the HTTP code returned for type GetMetricsNamesOK
const GetMetricsNamesOKCode int = 200

/*
GetMetricsNamesOK success

swagger:response getMetricsNamesOK
*/
type GetMetricsNamesOK struct {

	/*
	  In: Body
	*/
	Payload []string `json:"body,omitempty"`
}

// NewGetMetricsNamesOK creates GetMetricsNamesOK with default headers values

func NewGetMetricsNamesOK() *GetMetricsNamesOK {

	return &GetMetricsNamesOK{}
}

// WithPayload adds the payload to the get metrics names o k response
func (o *GetMetricsNamesOK) WithPayload(payload []string) *GetMetricsNamesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get metrics names o k response
func (o *GetMetricsNamesOK) SetPayload(payload []string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMetricsNamesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]string, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetMetricsNamesBadRequestCode is the HTTP code returned for type GetMetricsNamesBadRequest
const GetMetricsNamesBadRequestCode int = 400

/*
GetMetricsNamesBadRequest bad request

swagger:response getMetricsNamesBadRequest
*/
type GetMetricsNamesBadRequest struct {
}

// NewGetMetricsNamesBadRequest creates GetMetricsNamesBadRequest with default headers values

func NewGetMetricsNamesBadRequest() *lhttp.HttpError {
	return &lhttp.HttpError{
		Code: 400,
	}
}

// WriteResponse to the client
func (o *GetMetricsNamesBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetMetricsNamesInternalServerErrorCode is the HTTP code returned for type GetMetricsNamesInternalServerError
const GetMetricsNamesInternalServerErrorCode int = 500

/*
GetMetricsNamesInternalServerError internal service error

swagger:response getMetricsNamesInternalServerError
*/
type GetMetricsNamesInternalServerError struct {
}

// NewGetMetricsNamesInternalServerError creates GetMetricsNamesInternalServerError with default headers values

func NewGetMetricsNamesInternalServerError() *lhttp.HttpError {
	return &lhttp.HttpError{
		Code: 500,
	}
}

// WriteResponse to the client
func (o *GetMetricsNamesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
