// Code generated by go-swagger; DO NOT EDIT.

package metrics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetMetricsNamesHandlerFunc turns a function with the right signature into a get metrics names handler
type GetMetricsNamesHandlerFunc func(GetMetricsNamesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetMetricsNamesHandlerFunc) Handle(params GetMetricsNamesParams) middleware.Responder {
	return fn(params)
}

// GetMetricsNamesHandler interface for that can handle valid get metrics names params
type GetMetricsNamesHandler interface {
	Handle(GetMetricsNamesParams) middleware.Responder
}

// NewGetMetricsNames creates a new http.Handler for the get metrics names operation
func NewGetMetricsNames(ctx *middleware.Context, handler GetMetricsNamesHandler) *GetMetricsNames {
	return &GetMetricsNames{Context: ctx, Handler: handler}
}

/*
	GetMetricsNames swagger:route GET /metrics/names metrics getMetricsNames

List metric names for an experiment.

List monitoring metric names for an experiment
*/
type GetMetricsNames struct {
	Context *middleware.Context
	Handler GetMetricsNamesHandler
}

func (o *GetMetricsNames) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetMetricsNamesParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
