// Code generated by go-swagger; DO NOT EDIT.

package metrics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	lhttp "github.infra.cloudera.com/CAI/AmpRagMonitoring/pkg/http"

	"github.infra.cloudera.com/CAI/AmpRagMonitoring/models"
)

// PostMetricsListOKCode is the HTTP code returned for type PostMetricsListOK
const PostMetricsListOKCode int = 200

/*
PostMetricsListOK success

swagger:response postMetricsListOK
*/
type PostMetricsListOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Metric `json:"body,omitempty"`
}

// NewPostMetricsListOK creates PostMetricsListOK with default headers values

func NewPostMetricsListOK() *PostMetricsListOK {

	return &PostMetricsListOK{}
}

// WithPayload adds the payload to the post metrics list o k response
func (o *PostMetricsListOK) WithPayload(payload []*models.Metric) *PostMetricsListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post metrics list o k response
func (o *PostMetricsListOK) SetPayload(payload []*models.Metric) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostMetricsListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Metric, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// PostMetricsListBadRequestCode is the HTTP code returned for type PostMetricsListBadRequest
const PostMetricsListBadRequestCode int = 400

/*
PostMetricsListBadRequest bad request

swagger:response postMetricsListBadRequest
*/
type PostMetricsListBadRequest struct {
}

// NewPostMetricsListBadRequest creates PostMetricsListBadRequest with default headers values

func NewPostMetricsListBadRequest() *lhttp.HttpError {
	return &lhttp.HttpError{
		Code: 400,
	}
}

// WriteResponse to the client
func (o *PostMetricsListBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PostMetricsListInternalServerErrorCode is the HTTP code returned for type PostMetricsListInternalServerError
const PostMetricsListInternalServerErrorCode int = 500

/*
PostMetricsListInternalServerError internal service error

swagger:response postMetricsListInternalServerError
*/
type PostMetricsListInternalServerError struct {
}

// NewPostMetricsListInternalServerError creates PostMetricsListInternalServerError with default headers values

func NewPostMetricsListInternalServerError() *lhttp.HttpError {
	return &lhttp.HttpError{
		Code: 500,
	}
}

// WriteResponse to the client
func (o *PostMetricsListInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
