// Code generated by go-swagger; DO NOT EDIT.

package metrics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	lhttp "github.infra.cloudera.com/CAI/AmpRagMonitoring/pkg/http"
)

// PostMetricsOKCode is the HTTP code returned for type PostMetricsOK
const PostMetricsOKCode int = 200

/*
PostMetricsOK success

swagger:response postMetricsOK
*/
type PostMetricsOK struct {
}

// NewPostMetricsOK creates PostMetricsOK with default headers values

func NewPostMetricsOK() *PostMetricsOK {

	return &PostMetricsOK{}
}

// WriteResponse to the client
func (o *PostMetricsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostMetricsBadRequestCode is the HTTP code returned for type PostMetricsBadRequest
const PostMetricsBadRequestCode int = 400

/*
PostMetricsBadRequest bad request

swagger:response postMetricsBadRequest
*/
type PostMetricsBadRequest struct {
}

// NewPostMetricsBadRequest creates PostMetricsBadRequest with default headers values

func NewPostMetricsBadRequest() *lhttp.HttpError {
	return &lhttp.HttpError{
		Code: 400,
	}
}

// WriteResponse to the client
func (o *PostMetricsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PostMetricsInternalServerErrorCode is the HTTP code returned for type PostMetricsInternalServerError
const PostMetricsInternalServerErrorCode int = 500

/*
PostMetricsInternalServerError internal service error

swagger:response postMetricsInternalServerError
*/
type PostMetricsInternalServerError struct {
}

// NewPostMetricsInternalServerError creates PostMetricsInternalServerError with default headers values

func NewPostMetricsInternalServerError() *lhttp.HttpError {
	return &lhttp.HttpError{
		Code: 500,
	}
}

// WriteResponse to the client
func (o *PostMetricsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
