// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package lsql

import (
	"github.infra.cloudera.com/CAI/AmpRagMonitoring/pkg/test"
)

import (
	_ "modernc.org/sqlite"
)

// Injectors from wire.go:

func initializeTest(t ltest.T) (*Instance, error) {
	config, err := NewTestingConfig(t)
	if err != nil {
		return nil, err
	}
	instance, err := NewInstance(config)
	if err != nil {
		return nil, err
	}
	return instance, nil
}
