// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.infra.cloudera.com/CAI/AmpRagMonitoring/restapi/operations/experiments"
	"github.infra.cloudera.com/CAI/AmpRagMonitoring/restapi/operations/metrics"
	"github.infra.cloudera.com/CAI/AmpRagMonitoring/restapi/operations/runs"
)

// NewMetricsAPI creates a new Metrics instance
func NewMetricsAPI(spec *loads.Document) *MetricsAPI {
	return &MetricsAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		useSwaggerUI:        false,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer: runtime.JSONConsumer(),

		JSONProducer: runtime.JSONProducer(),

		RunsDeleteRunsHandler: runs.DeleteRunsHandlerFunc(func(params runs.DeleteRunsParams) middleware.Responder {
			return middleware.NotImplemented("operation runs.DeleteRuns has not yet been implemented")
		}),
		ExperimentsGetExperimentsHandler: experiments.GetExperimentsHandlerFunc(func(params experiments.GetExperimentsParams) middleware.Responder {
			return middleware.NotImplemented("operation experiments.GetExperiments has not yet been implemented")
		}),
		MetricsGetMetricsNamesHandler: metrics.GetMetricsNamesHandlerFunc(func(params metrics.GetMetricsNamesParams) middleware.Responder {
			return middleware.NotImplemented("operation metrics.GetMetricsNames has not yet been implemented")
		}),
		MetricsPostMetricsHandler: metrics.PostMetricsHandlerFunc(func(params metrics.PostMetricsParams) middleware.Responder {
			return middleware.NotImplemented("operation metrics.PostMetrics has not yet been implemented")
		}),
		MetricsPostMetricsListHandler: metrics.PostMetricsListHandlerFunc(func(params metrics.PostMetricsListParams) middleware.Responder {
			return middleware.NotImplemented("operation metrics.PostMetricsList has not yet been implemented")
		}),
		RunsPostRunsHandler: runs.PostRunsHandlerFunc(func(params runs.PostRunsParams) middleware.Responder {
			return middleware.NotImplemented("operation runs.PostRuns has not yet been implemented")
		}),
		RunsPostRunsListHandler: runs.PostRunsListHandlerFunc(func(params runs.PostRunsListParams) middleware.Responder {
			return middleware.NotImplemented("operation runs.PostRunsList has not yet been implemented")
		}),
	}
}

/*MetricsAPI API for creating and fetching metrics */
type MetricsAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	useSwaggerUI    bool

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator

	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator

	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// RunsDeleteRunsHandler sets the operation handler for the delete runs operation
	RunsDeleteRunsHandler runs.DeleteRunsHandler
	// ExperimentsGetExperimentsHandler sets the operation handler for the get experiments operation
	ExperimentsGetExperimentsHandler experiments.GetExperimentsHandler
	// MetricsGetMetricsNamesHandler sets the operation handler for the get metrics names operation
	MetricsGetMetricsNamesHandler metrics.GetMetricsNamesHandler
	// MetricsPostMetricsHandler sets the operation handler for the post metrics operation
	MetricsPostMetricsHandler metrics.PostMetricsHandler
	// MetricsPostMetricsListHandler sets the operation handler for the post metrics list operation
	MetricsPostMetricsListHandler metrics.PostMetricsListHandler
	// RunsPostRunsHandler sets the operation handler for the post runs operation
	RunsPostRunsHandler runs.PostRunsHandler
	// RunsPostRunsListHandler sets the operation handler for the post runs list operation
	RunsPostRunsListHandler runs.PostRunsListHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// UseRedoc for documentation at /docs
func (o *MetricsAPI) UseRedoc() {
	o.useSwaggerUI = false
}

// UseSwaggerUI for documentation at /docs
func (o *MetricsAPI) UseSwaggerUI() {
	o.useSwaggerUI = true
}

// SetDefaultProduces sets the default produces media type
func (o *MetricsAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *MetricsAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *MetricsAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *MetricsAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *MetricsAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *MetricsAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *MetricsAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the MetricsAPI
func (o *MetricsAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.RunsDeleteRunsHandler == nil {
		unregistered = append(unregistered, "runs.DeleteRunsHandler")
	}
	if o.ExperimentsGetExperimentsHandler == nil {
		unregistered = append(unregistered, "experiments.GetExperimentsHandler")
	}
	if o.MetricsGetMetricsNamesHandler == nil {
		unregistered = append(unregistered, "metrics.GetMetricsNamesHandler")
	}
	if o.MetricsPostMetricsHandler == nil {
		unregistered = append(unregistered, "metrics.PostMetricsHandler")
	}
	if o.MetricsPostMetricsListHandler == nil {
		unregistered = append(unregistered, "metrics.PostMetricsListHandler")
	}
	if o.RunsPostRunsHandler == nil {
		unregistered = append(unregistered, "runs.PostRunsHandler")
	}
	if o.RunsPostRunsListHandler == nil {
		unregistered = append(unregistered, "runs.PostRunsListHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *MetricsAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *MetricsAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	return nil
}

// Authorizer returns the registered authorizer
func (o *MetricsAPI) Authorizer() runtime.Authorizer {
	return nil
}

// ConsumersFor gets the consumers for the specified media types.
// MIME type parameters are ignored here.
func (o *MetricsAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *MetricsAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *MetricsAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the metrics API
func (o *MetricsAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *MetricsAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/runs"] = runs.NewDeleteRuns(o.context, o.RunsDeleteRunsHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/experiments"] = experiments.NewGetExperiments(o.context, o.ExperimentsGetExperimentsHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/metrics/names"] = metrics.NewGetMetricsNames(o.context, o.MetricsGetMetricsNamesHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/metrics"] = metrics.NewPostMetrics(o.context, o.MetricsPostMetricsHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/metrics/list"] = metrics.NewPostMetricsList(o.context, o.MetricsPostMetricsListHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/runs"] = runs.NewPostRuns(o.context, o.RunsPostRunsHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/runs/list"] = runs.NewPostRunsList(o.context, o.RunsPostRunsListHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *MetricsAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	if o.useSwaggerUI {
		return o.context.APIHandlerSwaggerUI(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *MetricsAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *MetricsAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *MetricsAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *MetricsAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[method][path] = builder(h)
	}
}
